### ISSUE TITLE
Hey new hack the box animation with particle.js

### ISSUE THREAD

**Issue by nyxb** [SheltonTolbert/near-field-particle-js#1]
Can you make these too? That would be super awesome I do not get it unfortunately.

**Comment by SheltonTolbert** [comment]
Are you talking about the animation on [this](https://app.hackthebox.com/login) page?

**Comment by nyxb** [comment]
> Are you talking about the animation on [this](https://app.hackthebox.com/login) page?

yes

**Comment by nyxb** [comment]
@SheltonTolbert 

Is it possible that you provide it?

**Comment by VidarDev** [comment]
@SheltonTolbert 

Is it possible that you provide it?

**Comment by SheltonTolbert** [comment]
Probably not. I have never used Particle.js and I don't think I really have any need to learn it. From looking at the animation however, It looks like a simple two dimensional array of squares whose vertical positions are determined by using a sine function offset by the squares position. That should be enough to get ya going should you want to tackle it yourself. Feel free to tag me in pull requests and I can review the code for you.
